const messages=document.getElementById('messages'),input=document.getElementById('input'),form=document.getElementById('composer'),mic=document.getElementById('mic'),voiceStatus=document.getElementById('voiceStatus'),voiceTitle=document.getElementById('voiceTitle'),speakToggle=document.getElementById('speakToggle');
let history=[],voiceReplies=true,recognition=null,listening=false;
function add(role,text,extra=''){const el=document.createElement('div');el.className=`bubble ${role} ${extra}`;el.innerHTML=`<strong>${role==='user'?'You':'Tara'}</strong><p></p>`;el.querySelector('p').textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el}
function speak(text){if(!voiceReplies||!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.96;u.pitch=1.02;u.volume=1;u.lang=/[\u0C00-\u0C7F]/.test(text)?'te-IN':/[\u0900-\u097F]/.test(text)?'hi-IN':'en-IN';window.speechSynthesis.speak(u)}
async function send(text){text=text.trim();if(!text)return;add('user',text);history.push({role:'user',content:text});input.value='';input.style.height='auto';const typing=add('tara','Tara is thinking…','typing');try{const r=await fetch('/api/ai/chat',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({messages:history})});const data=await r.json();typing.remove();if(!r.ok||!data.success)throw new Error(data.error||'Tara AI is temporarily unavailable.');add('tara',data.reply);history.push({role:'assistant',content:data.reply});speak(data.reply)}catch(e){typing.remove();add('tara',e.message,'error')}}
form.addEventListener('submit',e=>{e.preventDefault();send(input.value)});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(input.value)}});input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,160)+'px'});speakToggle.addEventListener('click',()=>{voiceReplies=!voiceReplies;speakToggle.setAttribute('aria-pressed',String(voiceReplies));speakToggle.textContent=voiceReplies?'🔊 Voice replies: On':'🔇 Voice replies: Off';if(!voiceReplies&&'speechSynthesis' in window)window.speechSynthesis.cancel()});
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
function setListening(on){listening=on;mic.classList.toggle('listening',on);mic.querySelector('span').textContent=on?'⏹️':'🎙️';voiceTitle.textContent=on?'I’m listening…':'Tap to talk';voiceStatus.textContent=on?'Speak naturally — I’m listening':'Voice assistant ready'}
async function requestMic(){try{if(navigator.mediaDevices?.getUserMedia){const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop())}}catch(e){voiceStatus.textContent='Microphone permission is needed for voice input';throw e}}
if(SR){recognition=new SR();recognition.lang='en-IN';recognition.interimResults=false;recognition.continuous=false;recognition.onstart=()=>setListening(true);recognition.onend=()=>setListening(false);recognition.onerror=e=>{setListening(false);voiceStatus.textContent=e.error==='not-allowed'?'Allow microphone access in Chrome':'Could not hear that — try again'};recognition.onresult=e=>{const text=e.results[e.results.length-1][0].transcript;input.value=text;send(text)};mic.addEventListener('click',async()=>{try{if(listening){recognition.stop();return}await requestMic();recognition.lang=/[\u0C00-\u0C7F]/.test(input.value)?'te-IN':'en-IN';recognition.start()}catch{}})}else{mic.disabled=true;voiceStatus.textContent='Voice input is not supported by this browser'}
