const app=document.getElementById('app');
const symbol=new URLSearchParams(location.search).get('symbol');
const esc=s=>String(s??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const metric=(label,value)=>`<div class="metric"><small>${esc(label)}</small><strong>${esc(value)}</strong></div>`;
const money=v=>v==null?'—':'₹'+Number(v).toLocaleString('en-IN',{maximumFractionDigits:2});
const number=v=>v==null?'—':Number(v).toLocaleString('en-IN');
const pct=v=>v==null?'—':`${v>=0?'+':''}${Number(v).toFixed(2)}%`;
const ranges=[['1d','Daily'],['1w','Weekly'],['1m','Monthly'],['3m','3 Months'],['6m','6 Months'],['1y','1 Year'],['3y','3 Years'],['5y','5 Years'],['10y','10 Years'],['all','All Time']];

function sma(values,n){return values.map((_,i)=>i+1<n?null:values.slice(i-n+1,i+1).reduce((a,b)=>a+b,0)/n)}
function ema(values,n){if(!values.length)return[];const k=2/(n+1),out=[];let prev=values[0];values.forEach((v,i)=>{prev=i===0?v:v*k+prev*(1-k);out.push(prev)});return out}
function rsi(values,n=14){const out=Array(values.length).fill(null);if(values.length<=n)return out;let gain=0,loss=0;for(let i=1;i<=n;i++){const d=values[i]-values[i-1];if(d>=0)gain+=d;else loss-=d}let ag=gain/n,al=loss/n;out[n]=al===0?100:100-(100/(1+ag/al));for(let i=n+1;i<values.length;i++){const d=values[i]-values[i-1],g=Math.max(d,0),l=Math.max(-d,0);ag=(ag*(n-1)+g)/n;al=(al*(n-1)+l)/n;out[i]=al===0?100:100-(100/(1+ag/al))}return out}
function macd(values){const e12=ema(values,12),e26=ema(values,26),line=values.map((_,i)=>e12[i]-e26[i]),signal=ema(line,9);return{line,signal,hist:line.map((v,i)=>v-signal[i])}}
function trendLabel(rows){if(rows.length<20)return'Insufficient history';const closes=rows.map(r=>Number(r.close)).filter(Number.isFinite),fast=sma(closes,20),slow=sma(closes,50);const last=closes.at(-1),f=fast.at(-1),s=slow.at(-1);if(s==null)return'Building';if(last>f&&f>s)return'Bullish structure';if(last<f&&f<s)return'Bearish structure';return'Neutral / mixed'}
function linePath(points){return points.filter(Boolean).map((p,i)=>`${i?'L':'M'} ${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join(' ')}

function renderTradingAnalysisShell(){return `<section class="panel wide trading-panel" id="tradingAnalysis"><div class="trading-head"><div><div class="eyebrow">TARA AI • TECHNICAL INTELLIGENCE</div><h2>Trading analysis</h2><p>Price action, trend, momentum, volume and key levels in one evidence-first view.</p></div><div class="analysis-badge"><span class="pulse"></span><span id="analysisSource">Waiting for verified market data</span></div></div><div id="tradingBody"><div class="history-empty">Connect an authorized market-data source to generate Tara's live technical picture.</div></div></section>`}

function renderTradingAnalysis(rows,data){
 const body=document.getElementById('tradingBody');if(!body||!rows.length)return;
 const clean=rows.filter(r=>Number.isFinite(Number(r.close))&&Number.isFinite(Number(r.high))&&Number.isFinite(Number(r.low))).slice(-90);if(clean.length<20){body.innerHTML='<div class="history-empty"><strong>Not enough verified sessions for technical analysis.</strong><p>Tara will show the full chart when sufficient source-backed history is available.</p></div>';return}
 const closes=clean.map(r=>Number(r.close)), highs=clean.map(r=>Number(r.high)), lows=clean.map(r=>Number(r.low)), vols=clean.map(r=>Number(r.volume)||0);
 const ma20=sma(closes,20),ma50=sma(closes,50),rv=vols.length?vols.reduce((a,b)=>a+b,0)/vols.length:0,rs=rsi(closes),m=macd(closes),last=closes.at(-1),lastR=rs.at(-1),lastMacd=m.line.at(-1),lastSignal=m.signal.at(-1);
 const hi=Math.max(...highs),lo=Math.min(...lows),pad=(hi-lo)*.08||1,minY=lo-pad,maxY=hi+pad,W=980,H=330,left=54,right=18,top=28,bottom=36,plotW=W-left-right,plotH=H-top-bottom,step=plotW/Math.max(clean.length-1,1),y=v=>top+(maxY-v)/(maxY-minY)*plotH,x=i=>left+i*step;
 const candles=clean.map((r,i)=>{const cx=x(i),cw=Math.max(3,Math.min(9,step*.58)),yo=y(Number(r.open)),yc=y(Number(r.close)),yh=y(Number(r.high)),yl=y(Number(r.low)),up=Number(r.close)>=Number(r.open);return `<g class="candle ${up?'up':'down'}"><line x1="${cx}" y1="${yh}" x2="${cx}" y2="${yl}"/><rect x="${cx-cw/2}" y="${Math.min(yo,yc)}" width="${cw}" height="${Math.max(1,Math.abs(yc-yo))}" rx="1.5"/></g>`}).join('');
 const ma20Path=linePath(ma20.map((v,i)=>v==null?null:[x(i),y(v)]));const ma50Path=linePath(ma50.map((v,i)=>v==null?null:[x(i),y(v)]));
 const levels=[lo,hi,(lo+hi)/2];
 const grid=levels.map(v=>`<g><line class="chart-grid" x1="${left}" y1="${y(v)}" x2="${W-right}" y2="${y(v)}"/><text class="chart-label" x="${left-8}" y="${y(v)+4}" text-anchor="end">${money(v)}</text></g>`).join('');
 const bars=clean.map((r,i)=>{const maxV=Math.max(...vols)||1,h=(vols[i]/maxV)*50;return `<rect class="volume-bar" x="${x(i)-Math.max(2,step*.28)}" y="${H-18-h}" width="${Math.max(3,step*.56)}" height="${h}" rx="2"/>`}).join('');
 const trend=trendLabel(clean),volumeState=vols.at(-1)>rv*1.5?'High participation':vols.at(-1)>rv?'Above average':'Normal participation';
 const signalParts=[last>ma20.at(-1)?'Price > SMA20':'Price < SMA20',last>ma50.at(-1)?'Price > SMA50':'Price < SMA50',lastR!=null?(lastR>=55?'RSI positive':lastR<=45?'RSI weak':'RSI neutral'):'RSI unavailable',lastMacd>lastSignal?'MACD positive':'MACD negative'];
 const score=signalParts.filter(s=>/Price >|positive/.test(s)).length;
 document.getElementById('analysisSource').textContent=`${clean.length} verified sessions • ${data.source||'authorized provider'}`;
 body.innerHTML=`<div class="analysis-strip"><div class="analysis-stat"><small>Trend</small><strong>${esc(trend)}</strong></div><div class="analysis-stat"><small>Last close</small><strong>${money(last)}</strong></div><div class="analysis-stat"><small>RSI (14)</small><strong>${lastR==null?'—':lastR.toFixed(1)}</strong></div><div class="analysis-stat"><small>Volume</small><strong>${esc(volumeState)}</strong></div><div class="analysis-stat"><small>Confluence</small><strong>${score}/4 aligned</strong></div></div>
 <div class="chart-card"><div class="chart-toolbar"><span>90-session price action</span><span><i class="legend-price"></i> Price <i class="legend-ma20"></i> SMA 20 <i class="legend-ma50"></i> SMA 50</span></div><div class="chart-scroll"><svg class="tara-chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Tara AI technical price chart">${grid}${candles}<path class="ma20" d="${ma20Path}"/><path class="ma50" d="${ma50Path}"/>${bars}</svg></div></div>
 <div class="indicator-grid"><div class="indicator-card"><div><span>Momentum • RSI (14)</span><b>${lastR==null?'—':lastR.toFixed(1)}</b></div><div class="meter"><span style="width:${Math.max(0,Math.min(100,lastR||0))}%"></span></div><small>${lastR>=70?'Overbought zone':lastR<=30?'Oversold zone':'Neutral momentum zone'}</small></div><div class="indicator-card"><div><span>MACD</span><b>${lastMacd>lastSignal?'Positive':'Negative'}</b></div><div class="macd-line"><span class="macd-pos" style="width:${Math.max(8,Math.min(92,50+(lastMacd-lastSignal)*100))}%"></span></div><small>12 / 26 / 9 configuration • confirmation, not certainty</small></div><div class="indicator-card"><div><span>Key range</span><b>${money(lo)} — ${money(hi)}</b></div><div class="level-row"><span>Support zone</span><strong>${money(lo)}</strong></div><div class="level-row"><span>Resistance zone</span><strong>${money(hi)}</strong></div></div></div>
 <div class="analysis-explain"><div><b>Tara reading</b><p>${esc(trend)}. ${esc(volumeState)}. Signals are derived from the verified historical series and are presented as evidence, not guaranteed future direction.</p></div><div><b>Decision discipline</b><p>Confirm price structure, momentum, participation and risk before any trade. A single indicator never becomes a standalone buy/sell instruction.</p></div></div>`;
}

function renderHistoryShell(){return `<div class="panel wide history-panel" id="history"><div class="history-head"><div><h2>Market history</h2><p>Source-backed historical OHLCV across every supported period.</p></div><span class="history-status" id="historyStatus">Checking data source…</span></div><div class="range-tabs" role="tablist">${ranges.map(([key,label],i)=>`<button class="range-tab${i===5?' active':''}" data-range="${key}" role="tab">${label}</button>`).join('')}</div><div id="historyBody" class="history-body"><div class="history-empty">Select a period to load historical market data.</div></div></div>`}

function renderHistory(data,range){
 const rows=data.rows||[];const latest=rows[rows.length-1],first=rows[0];const periodChange=first?.close&&latest?.close?((latest.close-first.close)/first.close)*100:null;const maxHigh=rows.reduce((m,r)=>r.high!=null?Math.max(m,r.high):m,null);const minLow=rows.reduce((m,r)=>r.low!=null?Math.min(m,r.low):m,null);const volume=rows.reduce((s,r)=>s+(r.volume||0),0);document.getElementById('historyStatus').textContent=`${rows.length.toLocaleString('en-IN')} sessions • ${esc(data.source||'Provider')}`;document.getElementById('historyBody').innerHTML=`<div class="history-summary">${metric('Period return',pct(periodChange))}${metric('Period high',money(maxHigh))}${metric('Period low',money(minLow))}${metric('Total volume',number(volume))}</div><div class="history-table-wrap"><table class="history-table"><thead><tr><th>Date</th><th>Open</th><th>High</th><th>Low</th><th>Close</th><th>Volume</th><th>Traded value</th></tr></thead><tbody>${rows.slice(-250).reverse().map(r=>`<tr><td>${esc(String(r.date).slice(0,10))}</td><td>${money(r.open)}</td><td>${money(r.high)}</td><td>${money(r.low)}</td><td>${money(r.close)}</td><td>${number(r.volume)}</td><td>${money(r.tradedValue)}</td></tr>`).join('')}</tbody></table></div><p class="history-foot">${rows.length>250?'Showing the latest 250 sessions in the table.':'Complete returned history shown.'} • Range: ${esc(range)} • As of ${esc(data.asOf)}</p>`;
}

async function loadHistory(range='1y'){
 const body=document.getElementById('historyBody'),status=document.getElementById('historyStatus');if(!body)return;body.innerHTML='<div class="history-loading">Loading verified historical market data…</div>';status.textContent='Loading…';document.querySelectorAll('.range-tab').forEach(b=>b.classList.toggle('active',b.dataset.range===range));
 try{const r=await fetch(`/api/market-history/${encodeURIComponent(symbol)}?range=${encodeURIComponent(range)}`,{cache:'no-store',headers:{Accept:'application/json'}});const d=await r.json();if(!r.ok||!d.success)throw new Error(d?.error||'Historical data unavailable');renderHistory(d,range);renderTradingAnalysis(d.rows||[],d);}catch(e){status.textContent='Data unavailable';body.innerHTML=`<div class="history-empty"><strong>Historical data is not connected yet.</strong><p>${esc(e.message)}</p><small>No fabricated prices are displayed. Connect an authorized/licensed EOD provider to populate Daily through All Time.</small></div>`;const tb=document.getElementById('tradingBody');if(tb)tb.innerHTML='<div class="history-empty"><strong>Tara technical picture is waiting for verified market data.</strong><p>No fabricated chart or signal is shown.</p></div>';}}

async function loadPreviousTradingDay(){const box=document.getElementById('previousDayBody');if(!box)return;try{const r=await fetch(`/api/market-history/${encodeURIComponent(symbol)}/previous`,{cache:'no-store',headers:{Accept:'application/json'}});const d=await r.json();if(!r.ok||!d.success)throw new Error(d?.error||'Previous trading-day data unavailable');const x=d.rows?.[0];box.innerHTML=`<div class="history-summary">${metric('Trading date',String(x.date).slice(0,10))}${metric('Open',money(x.open))}${metric('High',money(x.high))}${metric('Low',money(x.low))}${metric('Close',money(x.close))}${metric('Volume',number(x.volume))}${metric('Traded value',money(x.tradedValue))}</div><p class="history-foot">Source: ${esc(d.source)} • As of ${esc(d.asOf)}</p>`;}catch(e){box.innerHTML=`<div class="history-empty"><strong>Previous trading-day data unavailable.</strong><p>${esc(e.message)}</p></div>`;}}

async function load(){
 if(!symbol){app.innerHTML='<div class="error">No company symbol was supplied.</div>';return}
 try{const r=await fetch(`/api/companies?q=${encodeURIComponent(symbol)}&limit=10`,{cache:'no-store'});const d=await r.json();const c=(d.results||[]).find(x=>x.symbol===symbol)||(d.results||[])[0];if(!r.ok||!c)throw new Error('Company not found in the NSE security master.');document.title=`Tara AI — ${c.name}`;
 app.innerHTML=`<div class="wrap"><section class="hero"><div><div class="eyebrow">INDIA • NSE EQUITY</div><h1>${esc(c.name)}</h1><div class="meta"><b>${esc(c.symbol)}</b> · ISIN ${esc(c.isin)} · Series ${esc(c.series||'EQ')}</div></div><div class="status"><span class="dot">●</span> Verified company master<br><small>Source: NSE security master</small></div></section><section class="grid"><div class="panel"><h2>Company identity</h2>${metric('Exchange',c.exchange)}${metric('NSE Symbol',c.symbol)}${metric('ISIN',c.isin)}${metric('Series',c.series||'EQ')}</div><div class="panel"><h2>Market snapshot</h2>${metric('LTP','Live feed not connected')}${metric('Today %','—')}${metric('Day High / Low','—')}${metric('Volume','—')}</div><div class="panel"><h2>Financial intelligence</h2>${metric('Revenue','Not loaded')}${metric('Net Profit','Not loaded')}${metric('EPS / P-E','Not loaded')}${metric('ROE / ROCE','Not loaded')}</div><div class="panel wide"><h2>Previous trading day</h2><div id="previousDayBody" class="history-body"><div class="history-loading">Checking previous trading-day data…</div></div></div>${renderTradingAnalysisShell()}${renderHistoryShell()}<div class="panel wide"><h2>Official company sources</h2><div class="links"><a target="_blank" rel="noopener" href="${esc(c.nseUrl)}">NSE Quote ↗</a><a target="_blank" rel="noopener" href="https://www.nseindia.com/companies-listing/corporate-filings-financial-results?symbol=${encodeURIComponent(c.symbol)}">Financial Results ↗</a><a target="_blank" rel="noopener" href="https://www.nseindia.com/companies-listing/corporate-filings-announcements?symbol=${encodeURIComponent(c.symbol)}">Announcements ↗</a><a target="_blank" rel="noopener" href="https://www.nseindia.com/companies-listing/corporate-filings-actions?symbol=${encodeURIComponent(c.symbol)}">Corporate Actions ↗</a><a target="_blank" rel="noopener" href="https://www.bseindia.com/">BSE India ↗</a></div></div><div class="panel wide"><h2>Tara AI analysis status</h2><p class="note">The technical picture uses only source-backed historical OHLCV. Tara does not fabricate missing prices or guarantee future market direction.</p><div class="locked">Technical pipeline: Price Action → Trend → Support/Resistance → Volume → RSI → MACD → Confluence → Risk-aware scenario analysis.</div></div></section></div>`;
 document.querySelectorAll('.range-tab').forEach(btn=>btn.addEventListener('click',()=>loadHistory(btn.dataset.range)));loadPreviousTradingDay();loadHistory('1y');
 }catch(e){app.innerHTML=`<div class="error">${esc(e.message)}</div>`}}
load();
