const companies = {
  RELIANCE:{name:'Reliance Industries Limited',symbol:'RELIANCE',exchange:'NSE / BSE',sector:'Oil, Gas, Telecom, Retail',website:'https://www.ril.com',founded:'1966',description:'Diversified Indian conglomerate with businesses spanning energy, petrochemicals, digital services and retail.',events:[['1966','Reliance Commercial Corporation established.'],['1977','Reliance Industries listed after its public issue.'],['2002','Group leadership transitioned after the passing of Dhirubhai Ambani.'],['2016','Jio commercial services launched.'],['2020','Global strategic investment programme in Jio Platforms.'],['2024','Retail and digital businesses continued large-scale expansion.'],['2026','Current profile should be refreshed from exchange filings and company disclosures before analysis.']],metrics:[['NSE/BSE','Listed'],['History','1966 → today'],['Source','Company + exchanges'],['Status','Verify live']]},
  TCS:{name:'Tata Consultancy Services Limited',symbol:'TCS',exchange:'NSE / BSE',sector:'IT Services',website:'https://www.tcs.com',founded:'1968',description:'Tata Group technology and IT services company serving enterprises globally.',events:[['1968','Tata Computer Systems established.'],['1999','TCS became one of India’s major listed technology businesses through the Tata group restructuring.'],['2004','TCS listed on Indian stock exchanges.'],['2010s','Expanded global digital, cloud and consulting operations.'],['2024','Continued AI, cloud and digital transformation investments.'],['2026','Live filings and financial history should be pulled from authorized sources.']],metrics:[['NSE/BSE','Listed'],['History','1968 → today'],['Source','Company + exchanges'],['Status','Verify live']]},
  HDFCBANK:{name:'HDFC Bank Limited',symbol:'HDFCBANK',exchange:'NSE / BSE',sector:'Banking',website:'https://www.hdfcbank.com',founded:'1994',description:'Major Indian private-sector bank with retail, commercial and corporate banking operations.',events:[['1994','HDFC Bank incorporated.'],['1995','Commercial banking operations began.'],['2008','Centurion Bank of Punjab merger expanded the franchise.'],['2023','HDFC Ltd merger completed, creating a larger financial services institution.'],['2024','Post-merger integration and balance-sheet transition continued.'],['2026','Current filings must be refreshed from authorized exchange/company sources.']],metrics:[['NSE/BSE','Listed'],['History','1994 → today'],['Source','Company + exchanges'],['Status','Verify live']]},
  INFY:{name:'Infosys Limited',symbol:'INFY',exchange:'NSE / BSE',sector:'IT Services',website:'https://www.infosys.com',founded:'1981',description:'Global technology services and consulting company founded by N. R. Narayana Murthy and co-founders.',events:[['1981','Infosys founded in Pune.'],['1993','Infosys went public in India.'],['1999','Listed on NASDAQ through an ADR issue.'],['2010s','Expanded cloud, digital and global consulting capabilities.'],['2020s','Accelerated AI, cloud and digital transformation offerings.'],['2026','Refresh financials and corporate actions from authorized sources.']],metrics:[['NSE/BSE','Listed'],['History','1981 → today'],['Source','Company + exchanges'],['Status','Verify live']]},
  SBIN:{name:'State Bank of India',symbol:'SBIN',exchange:'NSE / BSE',sector:'Banking',website:'https://sbi.co.in',founded:'1806 / 1955',description:'India’s major public-sector banking institution with roots tracing to the Bank of Calcutta and the State Bank of India Act.',events:[['1806','Bank of Calcutta established, part of SBI’s institutional lineage.'],['1955','State Bank of India created under the SBI Act.'],['2008','Associate-bank consolidation process expanded the group.'],['2017','Five associate banks and Bharatiya Mahila Bank merged into SBI.'],['2020s','Digital banking and large-scale infrastructure expansion continued.'],['2026','Refresh current filings and market data from authorized sources.']],metrics:[['NSE/BSE','Listed'],['History','1806 → today'],['Source','Company + exchanges'],['Status','Verify live']]}
};

const copy = () => (NOVA_COPY && NOVA_COPY[window.NOVA_ACTIVE_LANGUAGE?.code] || NOVA_COPY['en-IN']);
function renderProfile(c){
 const t=copy();
 document.getElementById('results').innerHTML=`<article class="profile"><div class="profile-head"><div><span class="symbol">${c.symbol} · ${c.exchange}</span><h2>${c.name}</h2><p>${c.description}</p><a class="website" href="${c.website}" target="_blank" rel="noopener noreferrer">${t.website} ↗</a></div><div class="badges"><span class="badge">NSE</span><span class="badge">BSE</span><span class="badge">AI evidence profile</span></div></div><div class="tabs"><button class="tab active">${t.overview}</button><button class="tab">${t.financials}</button><button class="tab">${t.actions}</button><button class="tab">${t.filings}</button><button class="tab">${t.risk}</button></div><div class="metrics">${c.metrics.map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div><h3>${t.history}</h3><div class="timeline">${c.events.map(x=>`<div class="event"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div><div class="source">${t.sources}: <a href="https://www.nseindia.com/companies-listing/corporate-filings-application" target="_blank" rel="noopener">NSE Corporate Filings</a> · <a href="${c.website}" target="_blank" rel="noopener">${c.name}</a></div></article>`;
}
function searchCompany(value){
 const q=value.trim().toUpperCase();
 const c=companies[q] || Object.values(companies).find(x=>x.name.toUpperCase().includes(q));
 if(c) renderProfile(c); else document.getElementById('results').innerHTML=`<div class="empty">No local profile found for <b>${value}</b> yet.<br><br>Next data layer will connect the complete authorized NSE + BSE company universe.</div>`;
}
document.addEventListener('DOMContentLoaded',()=>{
 const sel=document.getElementById('language');
 NOVA_LANGUAGES.forEach(l=>{const o=document.createElement('option');o.value=l.code;o.textContent=`${l.short} · ${l.label}`;sel.appendChild(o)});
 sel.value=localStorage.getItem('nova_language')||'en-IN';
 sel.addEventListener('change',()=>{novaLanguage(sel.value); const q=document.getElementById('companySearch').value; if(q) searchCompany(q)});
 document.getElementById('searchBtn').onclick=()=>searchCompany(document.getElementById('companySearch').value);
 document.getElementById('companySearch').addEventListener('keydown',e=>{if(e.key==='Enter')searchCompany(e.target.value)});
 document.querySelectorAll('[data-symbol]').forEach(b=>b.onclick=()=>{document.getElementById('companySearch').value=b.dataset.symbol;searchCompany(b.dataset.symbol)});
 document.getElementById('speakIntro').onclick=()=>novaSpeak('Meet Nova. Your female AI market intelligence companion.');
 searchCompany('RELIANCE');
});
