const $=id=>document.getElementById(id);
const LANGS=[['en','English'],['hi','Hindi'],['te','Telugu'],['mr','Marathi'],['ta','Tamil'],['bn','Bengali'],['gu','Gujarati'],['kn','Kannada'],['ml','Malayalam'],['pa','Punjabi'],['or','Odia'],['as','Assamese'],['ur','Urdu'],['kok','Konkani'],['ne','Nepali']];
const language=$('language'); LANGS.forEach(([code,label])=>{const o=document.createElement('option');o.value=code;o.textContent=label;language.appendChild(o)});
language.value=localStorage.getItem('aarohi-lang')||'en';
function applyLang(){const t=AAROHI_I18N[language.value]||AAROHI_I18N.en;document.documentElement.lang=language.value;$('tag').textContent=t.tag;$('languageLabel').textContent=t.language;$('query').placeholder=t.search;$('companiesTitle').textContent=t.companies;$('historyText').textContent=t.history+' — '+t.verified;$('sourcesTitle').textContent=t.sources;$('disclaimer').textContent=t.disclaimer;localStorage.setItem('aarohi-lang',language.value)}
language.addEventListener('change',applyLang);applyLang();

let universe=[];
const money=v=>v==null?'—':'₹'+Number(v).toLocaleString('en-IN',{maximumFractionDigits:2});
const pct=v=>v==null?'—':`${v>=0?'+':''}${Number(v).toFixed(2)}%`;
const num=v=>v==null?'—':Number(v).toLocaleString('en-IN');
function metric(label,value,sub=''){return `<div class="fact"><small>${label}</small><b>${value}</b>${sub?`<span>${sub}</span>`:''}</div>`}
function card(c){return `<article class="company live-card" data-symbol="${c.symbol}"><div class="company-head"><div><h2>${c.name}</h2><span class="symbol">${c.symbol}</span><span class="isin">ISIN ${c.isin||'—'}</span></div><div class="badges"><span class="badge">${c.exchange||'NSE'}</span><span class="badge">${c.series||'EQ'}</span></div></div><div class="live-strip"><div class="live-dot"></div><strong>Today / Live market</strong><span class="freshness" data-freshness>Waiting for feed…</span></div><div class="facts live-facts">${metric('LTP','—')} ${metric('Today %','—')} ${metric('Open','—')} ${metric('Day High','—')} ${metric('Day Low','—')} ${metric('Volume','—')}</div><div class="profit-box"><div><small>Latest reported net profit</small><strong data-profit>Not loaded</strong></div><div><small>Data as of</small><strong data-asof>—</strong></div></div><p class="live-reason" data-reason>Live quote and latest company financial result will be shown here. No fabricated numbers.</p><div class="links"><a target="_blank" rel="noopener" href="${c.nseUrl||'https://www.nseindia.com/'}">NSE ↗</a><a target="_blank" rel="noopener" href="https://www.bseindia.com/">BSE ↗</a><a target="_blank" rel="noopener" href="${c.searchUrl||`https://www.nseindia.com/search?q=${encodeURIComponent(c.name)}`}" >Official disclosures ↗</a></div></article>`}
function render(list){$('results').innerHTML=list.length?list.map(card).join(''):`<div class="empty">No matching company found in the official company universe.</div>`;loadQuotes()}
async function fetchJson(url){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw new Error('Aarohi backend is not connected to this deployment. Static company search will be used when the daily universe file is available.')}if(!r.ok||!data.success)throw new Error(data?.error||'Company service unavailable');return data}
async function loadStaticUniverse(q=''){
  const r=await fetch('/data/companies.json',{cache:'no-store'}); if(!r.ok) throw new Error('Daily company universe is still being built.');
  const data=await r.json(); const rows=Array.isArray(data)?data:(data.results||[]); const needle=q.toLowerCase();
  const matches=needle?rows.filter(c=>`${c.name} ${c.symbol} ${c.isin}`.toLowerCase().includes(needle)):rows;
  universe=matches.slice(0,100); $('verifiedText').textContent=`${Number(rows.length).toLocaleString('en-IN')} NSE securities indexed • daily source update`; render(universe);
}
async function loadUniverse(q=''){$('results').innerHTML='<div class="empty">Loading the official NSE company universe…</div>';try{const data=await fetchJson(`/api/companies?limit=100${q?`&q=${encodeURIComponent(q)}`:''}`);universe=data.results||[];$('verifiedText').textContent=`${Number(data.total||0).toLocaleString('en-IN')} NSE securities indexed • source: NSE`;render(universe)}catch(apiError){try{await loadStaticUniverse(q)}catch(staticError){$('results').innerHTML=`<div class="empty"><strong>${staticError.message}</strong><br><br>Backend is required for live quotes. The daily company universe will be generated automatically by GitHub Actions.</div>`}}}
async function loadQuotes(){document.querySelectorAll('.live-card').forEach(async card=>{const symbol=card.dataset.symbol;try{const data=await fetchJson(`/api/live-market/quote/${encodeURIComponent(symbol)}`);const q=data.quote;const facts=card.querySelectorAll('.live-facts .fact b');[q.ltp,q.percentChange,q.open,q.high,q.low,q.volume].forEach((v,i)=>facts[i].textContent=i===1?pct(v):i===5?num(v):money(v));card.querySelector('[data-freshness]').textContent=`LIVE • ${new Date(q.asOf).toLocaleString('en-IN')}`;card.querySelector('[data-reason]').textContent=`Today: ${money(q.change)} (${pct(q.percentChange)}) from previous close. High ${money(q.high)}, low ${money(q.low)}.`}catch(e){card.querySelector('[data-freshness]').textContent='Live feed not connected';card.querySelector('[data-reason]').textContent='No live number is displayed until an authorized market-data feed is connected.'}})}
async function search(){await loadUniverse($('query').value.trim())}
$('searchBtn').addEventListener('click',search);$('query').addEventListener('keydown',e=>{if(e.key==='Enter')search()});
loadUniverse();setInterval(()=>{if(universe.length)loadQuotes()},15000);
