const $=id=>document.getElementById(id); const LANGS=[['en','English'],['hi','Hindi'],['te','Telugu'],['mr','Marathi'],['ta','Tamil'],['bn','Bengali'],['gu','Gujarati'],['kn','Kannada'],['ml','Malayalam'],['pa','Punjabi'],['or','Odia'],['as','Assamese'],['ur','Urdu'],['kok','Konkani'],['ne','Nepali']];
const language=$('language'); LANGS.forEach(([code,label])=>{const o=document.createElement('option');o.value=code;o.textContent=label;language.appendChild(o)}); language.value=localStorage.getItem('aarohi-lang')||'en';
function applyLang(){const t=AAROHI_I18N[language.value]||AAROHI_I18N.en;document.documentElement.lang=language.value;$('tag').textContent=t.tag;$('languageLabel').textContent=t.language;$('query').placeholder='Search company, NSE/BSE symbol, scrip code or ISIN';$('companiesTitle').textContent=t.companies;$('historyText').textContent='Search by company name, NSE symbol, BSE scrip code or ISIN. Open any company for its full Tara AI intelligence profile.';$('sourcesTitle').textContent=t.sources;$('disclaimer').textContent=t.disclaimer;localStorage.setItem('aarohi-lang',language.value)} language.addEventListener('change',applyLang);applyLang();
let universe=[]; const money=v=>v==null?'—':'₹'+Number(v).toLocaleString('en-IN',{maximumFractionDigits:2}); const pct=v=>v==null?'—':`${v>=0?'+':''}${Number(v).toFixed(2)}%`; const num=v=>v==null?'—':Number(v).toLocaleString('en-IN');
function metric(label,value,sub=''){return `<div class="fact"><small>${label}</small><b>${value}</b>${sub?`<span>${sub}</span>`:''}</div>`}
function card(c){const profile=`company-profile.html?symbol=${encodeURIComponent(c.symbol||c.nseSymbol||c.bseSymbol)}`;const exchanges=(c.exchanges||[]).join(' + ')||c.exchange||'—';const bseCode=c.bseCode||'Not mapped';return `<article class="company live-card" data-symbol="${c.nseSymbol||c.symbol||''}"><div class="company-head"><div><h2><a class="company-name" href="${profile}">${c.name}</a></h2><span class="symbol">${c.nseSymbol?`NSE ${c.nseSymbol}`:'NSE —'}</span><span class="isin">ISIN ${c.isin||'—'}</span></div><div class="badges"><span class="badge">${exchanges}</span><span class="badge">${c.series||'EQ'}</span></div></div><div class="exchange-row"><span>NSE: <b>${c.nseSymbol||'—'}</b></span><span>BSE: <b>${bseCode}</b></span></div><div class="live-strip"><div class="live-dot"></div><strong>Today / Live market</strong><span class="freshness" data-freshness>Waiting for feed…</span></div><div class="facts live-facts">${metric('LTP','—')} ${metric('Today %','—')} ${metric('Open','—')} ${metric('Day High','—')} ${metric('Day Low','—')} ${metric('Volume','—')}</div><div class="profit-box"><div><small>Latest reported net profit</small><strong data-profit>Not loaded</strong></div><div><small>Data as of</small><strong data-asof>—</strong></div></div><p class="live-reason" data-reason>Live quote and company financial data will be shown only when an authorized source is connected.</p><div class="links"><a href="${profile}">Company 360° ↗</a><a href="${profile}#history">History ↗</a>${c.nseUrl?`<a target="_blank" rel="noopener" href="${c.nseUrl}">NSE ↗</a>`:''}<a target="_blank" rel="noopener" href="${c.bseUrl||'https://www.bseindia.com/'}">BSE ↗</a></div></article>`}
function render(list){$('results').innerHTML=list.length?list.map(card).join(''):`<div class="empty">No matching company found in the verified company universe.</div>`;loadQuotes()}
async function fetchJson(url){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw new Error('Tara backend is not connected to this deployment.')}if(!r.ok||!data.success)throw new Error(data?.error||'Company service unavailable');return data}
async function loadUniverse(q=''){const filter=$('exchangeFilter').value;$('results').innerHTML='<div class="empty">Loading verified NSE + BSE company universe…</div>';try{const data=await fetchJson(`/api/companies?limit=500${q?`&q=${encodeURIComponent(q)}`:''}&exchange=${filter}`);universe=data.results||[];const c=data.coverage||{};$('verifiedText').textContent=`NSE ${Number(c.nse||0).toLocaleString('en-IN')} • BSE ${Number(c.bse||0).toLocaleString('en-IN')} • Both ${Number(c.both||0).toLocaleString('en-IN')} • ${data.source||'verified sources'}`;render(universe)}catch(e){$('results').innerHTML=`<div class="empty"><strong>Company universe unavailable.</strong><br>${e.message}<br><br>Tara AI will never invent a company record or fake BSE mapping.</div>`}}
async function loadQuotes(){document.querySelectorAll('.live-card').forEach(async card=>{const symbol=card.dataset.symbol;if(!symbol)return;try{const data=await fetchJson(`/api/live-market/quote/${encodeURIComponent(symbol)}`),q=data.quote,facts=card.querySelectorAll('.live-facts .fact b');[q.ltp,q.percentChange,q.open,q.high,q.low,q.volume].forEach((v,i)=>facts[i].textContent=i===1?pct(v):i===5?num(v):money(v));card.querySelector('[data-freshness]').textContent=`LIVE • ${new Date(q.asOf).toLocaleString('en-IN')}`;card.querySelector('[data-reason]').textContent=`Today: ${money(q.change)} (${pct(q.percentChange)}) • High ${money(q.high)} • Low ${money(q.low)}`}catch{card.querySelector('[data-freshness]').textContent='Live feed not connected';card.querySelector('[data-reason]').textContent='No live number is displayed until an authorized market-data feed is connected.'}})}
async function search(){await loadUniverse($('query').value.trim())} $('searchBtn').addEventListener('click',search);$('query').addEventListener('keydown',e=>{if(e.key==='Enter')search()});$('clearBtn').addEventListener('click',()=>{$('query').value='';loadUniverse()});$('exchangeFilter').addEventListener('change',search);loadUniverse();setInterval(()=>{if(universe.length)loadQuotes()},15000);
