window.AAROHI_I18N = {
  en:{name:'Aarohi',tag:'AI Market Intelligence',search:'Search company, symbol or ISIN',companies:'Companies',history:'Complete company history',sources:'Official sources',market:'Market',nse:'NSE',bse:'BSE',website:'Company website',language:'Language',verified:'Source-backed data',disclaimer:'Information only. Not investment advice.'},
  hi:{name:'आरोही',tag:'एआई मार्केट इंटेलिजेंस',search:'कंपनी, सिंबल या ISIN खोजें',companies:'कंपनियां',history:'कंपनी का पूरा इतिहास',sources:'आधिकारिक स्रोत',market:'बाज़ार',nse:'NSE',bse:'BSE',website:'कंपनी वेबसाइट',language:'भाषा',verified:'स्रोत-आधारित डेटा',disclaimer:'केवल जानकारी। निवेश सलाह नहीं।'},
  te:{name:'ఆరోహి',tag:'AI మార్కెట్ ఇంటెలిజెన్స్',search:'కంపెనీ, సింబల్ లేదా ISIN వెతకండి',companies:'కంపెనీలు',history:'కంపెనీ పూర్తి చరిత్ర',sources:'అధికారిక మూలాలు',market:'మార్కెట్',nse:'NSE',bse:'BSE',website:'కంపెనీ వెబ్‌సైట్',language:'భాష',verified:'మూలాధార డేటా',disclaimer:'సమాచారం కోసం మాత్రమే. పెట్టుబడి సలహా కాదు.'},
  mr:{name:'आरोही',tag:'AI मार्केट इंटेलिजन्स',search:'कंपनी, सिम्बॉल किंवा ISIN शोधा',companies:'कंपन्या',history:'कंपनीचा संपूर्ण इतिहास',sources:'अधिकृत स्रोत',market:'बाजार',nse:'NSE',bse:'BSE',website:'कंपनी वेबसाइट',language:'भाषा',verified:'स्रोत-आधारित डेटा',disclaimer:'फक्त माहिती. गुंतवणूक सल्ला नाही.'},
  ta:{name:'ஆரோஹி',tag:'AI சந்தை நுண்ணறிவு',search:'நிறுவனம், சின்னம் அல்லது ISIN தேடுங்கள்',companies:'நிறுவனங்கள்',history:'நிறுவனத்தின் முழு வரலாறு',sources:'அதிகாரப்பூர்வ ஆதாரங்கள்',market:'சந்தை',nse:'NSE',bse:'BSE',website:'நிறுவன இணையதளம்',language:'மொழி',verified:'ஆதார அடிப்படையிலான தரவு',disclaimer:'தகவலுக்காக மட்டும். முதலீட்டு ஆலோசனை அல்ல.'},
  bn:{name:'আরোহী',tag:'AI মার্কেট ইন্টেলিজেন্স',search:'কোম্পানি, সিম্বল বা ISIN খুঁজুন',companies:'কোম্পানি',history:'কোম্পানির সম্পূর্ণ ইতিহাস',sources:'অফিশিয়াল উৎস',market:'বাজার',nse:'NSE',bse:'BSE',website:'কোম্পানির ওয়েবসাইট',language:'ভাষা',verified:'উৎস-সমর্থিত ডেটা',disclaimer:'শুধু তথ্য। বিনিয়োগ পরামর্শ নয়।'},
  gu:{name:'આરોહી',tag:'AI માર્કેટ ઇન્ટેલિજન્સ',search:'કંપની, સિમ્બોલ અથવા ISIN શોધો',companies:'કંપનીઓ',history:'કંપનીનો સંપૂર્ણ ઇતિહાસ',sources:'સત્તાવાર સ્ત્રોતો',market:'બજાર',nse:'NSE',bse:'BSE',website:'કંપની વેબસાઇટ',language:'ભાષા',verified:'સ્ત્રોત આધારિત ડેટા',disclaimer:'માહિતી માટે. રોકાણ સલાહ નથી.'},
  kn:{name:'ಆರೋಹಿ',tag:'AI ಮಾರುಕಟ್ಟೆ ಬುದ್ಧಿಮತ್ತೆ',search:'ಕಂಪನಿ, ಸಿಂಬಲ್ ಅಥವಾ ISIN ಹುಡುಕಿ',companies:'ಕಂಪನಿಗಳು',history:'ಕಂಪನಿಯ ಸಂಪೂರ್ಣ ಇತಿಹಾಸ',sources:'ಅಧಿಕೃತ ಮೂಲಗಳು',market:'ಮಾರುಕಟ್ಟೆ',nse:'NSE',bse:'BSE',website:'ಕಂಪನಿ ವೆಬ್‌ಸೈಟ್',language:'ಭಾಷೆ',verified:'ಮೂಲಾಧಾರಿತ ಡೇಟಾ',disclaimer:'ಮಾಹಿತಿಗಾಗಿ ಮಾತ್ರ. ಹೂಡಿಕೆ ಸಲಹೆ ಅಲ್ಲ.'},
  ml:{name:'ആരോഹി',tag:'AI മാർക്കറ്റ് ഇന്റലിജൻസ്',search:'കമ്പനി, സിംബൽ അല്ലെങ്കിൽ ISIN തിരയുക',companies:'കമ്പനികൾ',history:'കമ്പനിയുടെ പൂർണ്ണ ചരിത്രം',sources:'ഔദ്യോഗിക ഉറവിടങ്ങൾ',market:'വിപണി',nse:'NSE',bse:'BSE',website:'കമ്പനി വെബ്സൈറ്റ്',language:'ഭാഷ',verified:'ഉറവിടാധിഷ്ഠിത ഡാറ്റ',disclaimer:'വിവരങ്ങൾക്കായി മാത്രം. നിക്ഷേപ ഉപദേശം അല്ല.'},
  pa:{name:'ਆਰੋਹੀ',tag:'AI ਮਾਰਕੀਟ ਇੰਟੈਲੀਜੈਂਸ',search:'ਕੰਪਨੀ, ਸਿੰਬਲ ਜਾਂ ISIN ਖੋਜੋ',companies:'ਕੰਪਨੀਆਂ',history:'ਕੰਪਨੀ ਦਾ ਪੂਰਾ ਇਤਿਹਾਸ',sources:'ਅਧਿਕਾਰਤ ਸਰੋਤ',market:'ਬਾਜ਼ਾਰ',nse:'NSE',bse:'BSE',website:'ਕੰਪਨੀ ਵੈੱਬਸਾਈਟ',language:'ਭਾਸ਼ਾ',verified:'ਸਰੋਤ-ਅਧਾਰਿਤ ਡਾਟਾ',disclaimer:'ਸਿਰਫ਼ ਜਾਣਕਾਰੀ। ਨਿਵੇਸ਼ ਸਲਾਹ ਨਹੀਂ।'},
  or:{name:'ଆରୋହୀ',tag:'AI ବଜାର ଇଣ୍ଟେଲିଜେନ୍ସ',search:'କମ୍ପାନୀ, ସିମ୍ବଲ୍ କିମ୍ବା ISIN ଖୋଜନ୍ତୁ',companies:'କମ୍ପାନୀ',history:'କମ୍ପାନୀର ସମ୍ପୂର୍ଣ୍ଣ ଇତିହାସ',sources:'ଅଧିକୃତ ଉତ୍ସ',market:'ବଜାର',nse:'NSE',bse:'BSE',website:'କମ୍ପାନୀ ୱେବସାଇଟ୍',language:'ଭାଷା',verified:'ଉତ୍ସ-ଆଧାରିତ ତଥ୍ୟ',disclaimer:'କେବଳ ସୂଚନା। ନିବେଶ ପରାମର୍ଶ ନୁହେଁ।'},
  as:{name:'আৰোহী',tag:'AI বজাৰ বুদ্ধিমত্তা',search:'কোম্পানী, চিহ্ন বা ISIN বিচাৰক',companies:'কোম্পানী',history:'কোম্পানীৰ সম্পূৰ্ণ ইতিহাস',sources:'আধিকাৰিক উৎস',market:'বজাৰ',nse:'NSE',bse:'BSE',website:'কোম্পানীৰ ৱেবছাইট',language:'ভাষা',verified:'উৎস-সমৰ্থিত তথ্য',disclaimer:'কেৱল তথ্য। বিনিয়োগ পৰামৰ্শ নহয়।'},
  ur:{name:'آروہی',tag:'AI مارکیٹ انٹیلیجنس',search:'کمپنی، سمبل یا ISIN تلاش کریں',companies:'کمپنیاں',history:'کمپنی کی مکمل تاریخ',sources:'سرکاری ذرائع',market:'مارکیٹ',nse:'NSE',bse:'BSE',website:'کمپنی ویب سائٹ',language:'زبان',verified:'ماخذ پر مبنی ڈیٹا',disclaimer:'صرف معلومات۔ سرمایہ کاری کا مشورہ نہیں۔'},
  kok:{name:'आरोही',tag:'AI बाजार इंटेलिजन्स',search:'कंपनी, सिम्बल वा ISIN सोदात',companies:'कंपन्यो',history:'कंपनीचो पुराय इतिहास',sources:'अधिकृत स्रोत',market:'बाजार',nse:'NSE',bse:'BSE',website:'कंपनी संकेतस्थळ',language:'भास',verified:'स्रोत-आधारित डेटा',disclaimer:'फकत म्हायती. गुंतवणूक सल्लो न्हय.'},
  ne:{name:'आरोही',tag:'AI बजार इन्टेलिजेन्स',search:'कम्पनी, सिम्बोल वा ISIN खोज्नुहोस्',companies:'कम्पनीहरू',history:'कम्पनीको पूर्ण इतिहास',sources:'आधिकारिक स्रोतहरू',market:'बजार',nse:'NSE',bse:'BSE',website:'कम्पनी वेबसाइट',language:'भाषा',verified:'स्रोत-आधारित डाटा',disclaimer:'जानकारीका लागि मात्र। लगानी सल्लाह होइन।'}
};
